
services:
  db:
    image: postgres:16-alpine
    restart: always
    # env_file:
    #   - ./backend/.env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_USER_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    # ports:
    #   - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    # env_file:
    #   - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    # env_file:
    #   - ./frontend/.env
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    depends_on:
      - backend

volumes:
  pgdata:
